In [1]:
import pandas as pd
import numpy as np
#!pip install igraph
from igraph import *

In [88]:
#!pip install xcffib
#!pip install cairocffi
#!pip install pycairo

Requirement already satisfied: xcffib in c:\users\leo\anaconda3\lib\site-packages (0.11.1)
Requirement already satisfied: six in c:\users\leo\anaconda3\lib\site-packages (from xcffib) (1.16.0)
Requirement already satisfied: cffi>=1.1.0 in c:\users\leo\anaconda3\lib\site-packages (from xcffib) (1.15.0)
Requirement already satisfied: pycparser in c:\users\leo\anaconda3\lib\site-packages (from cffi>=1.1.0->xcffib) (2.21)
Requirement already satisfied: cairocffi in c:\users\leo\anaconda3\lib\site-packages (1.0.0)
Requirement already satisfied: cffi>=1.1.0 in c:\users\leo\anaconda3\lib\site-packages (from cairocffi) (1.15.0)
Requirement already satisfied: pycparser in c:\users\leo\anaconda3\lib\site-packages (from cffi>=1.1.0->cairocffi) (2.21)

In [92]:
print(igraph.__version__)

0.10.0

In [ ]:
import xcffib
import cairocffi as cairo

In [2]:
#https://igraph.org/python/tutorial/latest/
g = Graph()

### Importando a Base

In [160]:
#Importando base
rh = pd.read_excel('rede_rh.xlsx')

In [161]:
rh.head()

     source   target  weight
0        Yu  Chapman       3
1     Gotti  Chapman       3
2    Oliver  Chapman       3
3     Snopp  Chapman       3
4  Gukrishn     Leon       1

### Criando Objeto Grafo a partir da base

In [162]:
#Criando objeto grafo a partir da base
rh = g.DataFrame(rh, directed=False, use_vids=False)

In [163]:
print(rh)

IGRAPH UNW- 18 35 --
+ attr: name (v), weight (e)
+ edges (vertex names):
   Angel -- Chang, Polark, Weng
Zhuo -- Christop, Gotti, Graffe, Hund, Nardo, Oliver, Patrick
   Chang -- Angel, Polark, Weng
 Chapman -- Gotti, Oliver, Snopp, Yu
Christop -- Gotti, Nardo, Yu, Zhuo
   Gotti -- Chapman, Christop, Kabutz, Leon, Nardo, Oliver, Patrick, Zhuo
  Graffe -- Hund, Yu, Zhuo
Gukrishn -- Kabutz, Leon, Snopp
    Hund -- Graffe, Zhuo
  Kabutz -- Gotti, Gukrishn, Leon, Snopp
    Leon -- Gotti, Gukrishn, Kabutz, Snopp
   Nardo -- Christop, Gotti, Zhuo
  Oliver -- Chapman, Gotti, Patrick, Zhuo
 Patrick -- Gotti, Oliver, Zhuo
  Polark -- Angel, Chang, Weng, Yu
   Snopp -- Chapman, Gukrishn, Kabutz, Leon
    Weng -- Angel, Chang, Polark
      Yu -- Chapman, Christop, Graffe, Polark

### Criando Tabela com os Nós para Preencher com as Propriedades

In [164]:
#Criando tabela com os nós
named_vertex_list = rh.vs()["name"]

In [165]:
named_vertex_list = pd.DataFrame(named_vertex_list)

In [166]:
named_vertex_list.rename(columns={0: 'node'})

        node
0      Angel
1      Chang
2    Chapman
3   Christop
4      Gotti
5     Graffe
6   Gukrishn
7       Hund
8     Kabutz
9       Leon
10     Nardo
11    Oliver
12   Patrick
13    Polark
14     Snopp
15      Weng
16        Yu
17      Zhuo

### Calculando as Proriedades e Montando a Tabela de Propriedades

In [167]:
#Inserindo propriedades dos nós
named_vertex_list['Degree'] = rh.degree()
named_vertex_list['cc'] = rh.transitivity_local_undirected()
named_vertex_list['betweenness'] = rh.betweenness()
named_vertex_list['betweenness_POND'] = rh.betweenness(weights='weight')
named_vertex_list['closeness'] = rh.closeness()
named_vertex_list['closeness_POND'] = rh.closeness(weights='weight')
named_vertex_list['excentricidade'] = rh.eccentricity()

#Inserindo propriedades da rede
named_vertex_list['nós'] = rh.vcount()
named_vertex_list['links'] = rh.ecount()
named_vertex_list['diametro'] = rh.diameter()
named_vertex_list['raio'] = rh.radius()
named_vertex_list['caminho medio'] = rh.average_path_length()
named_vertex_list['densidade'] = rh.density()

### Tabela Final para Análise

In [168]:
named_vertex_list.head(20)

,0,Degree,cc,betweenness,betweenness_POND,closeness,closeness_POND,excentricidade,nós,links,diametro,raio,caminho medio,densidade
0,Angel,3,1.000000,0.000000,0.000000,0.293103,0.188889,5.0,18,35,5,3,2.555556,0.228758
1,Chang,3,1.000000,0.000000,0.000000,0.293103,0.188889,5.0,18,35,5,3,2.555556,0.228758
2,Chapman,4,0.166667,31.600000,0.000000,0.500000,0.232877,3.0,18,35,5,3,2.555556,0.228758
3,Christop,4,0.500000,15.333333,39.166667,0.485714,0.369565,3.0,18,35,5,3,2.555556,0.228758
4,Gotti,8,0.285714,38.683333,58.166667,0.515152,0.386364,4.0,18,35,5,3,2.555556,0.228758
5,Graffe,3,0.333333,9.033333,10.833333,0.435897,0.326923,4.0,18,35,5,3,2.555556,0.228758
6,Gukrishn,3,1.000000,0.000000,0.000000,0.326923,0.250000,5.0,18,35,5,3,2.555556,0.228758
7,Hund,2,1.000000,0.000000,0.000000,0.369565,0.298246,4.0,18,35,5,3,2.555556,0.228758
8,Kabutz,4,0.666667,5.283333,13.000000,0.386364,0.309091,5.0,18,35,5,3,2.555556,0.228758
9,Leon,4,0.666667,5.283333,13.000000,0.386364,0.309091,5.0,18,35,5,3,2.555556,0.228758
10,Nardo,3,1.000000,0.000000,0.000000,0.425000,0.333333,4.0,18,35,5,3,2.555556,0.228758
11,Oliver,4,0.666667,3.033333,1.833333,0.447368,0.309091,4.0,18,35,5,3,2.555556,0.228758
12,Patrick,3,1.000000,0.000000,0.000000,0.377778,0.303571,5.0,18,35,5,3,2.555556,0.228758
13,Polark,4,0.500000,42.000000,42.000000,0.386364,0.223684,4.0,18,35,5,3,2.555556,0.228758
14,Snopp,4,0.500000,11.000000,2.000000,0.386364,0.253731,4.0,18,35,5,3,2.555556,0.228758
15,Weng,3,1.000000,0.000000,0.000000,0.293103,0.188889,5.0,18,35,5,3,2.555556,0.228758
16,Yu,4,0.000000,56.116667,52.333333,0.500000,0.303571,3.0,18,35,5,3,2.555556,0.228758
17,Zhuo,7,0.333333,20.633333,28.333333,0.472222,0.361702,4.0,18,35,5,3,2.555556,0.228758